import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import NextAuthProvider from "../context/NextAuthProvider";
import { authOptions } from "@/lib/auth";
import Header from "@/components/layouts/Header";
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  console.log("session: " + session);

  if (!session?.isAuthenticated) {
    return redirect("/auth/signin");
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <Header />
          {children}
          <ToastContainer />
        </NextAuthProvider>
        <ToastContainer />
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
